openapi: 3.0.0
info:
  title: API de Cocinando
  description: API para la gestión de usuarios y pagos en la aplicación Cocinando.
  contact:
    name: Cocinando Team
    email: niltongr@outlook.com
  version: 1.0.0

components:
  securitySchemes:
    jwtAuth:
      type: apiKey
      in: header
      name: Authorization

paths:
  /api/users:
    post:
      summary: Crea un nuevo usuario
      tags:
        - Usuarios
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - nombreCompleto
                - email
                - contrasena
                - rol_id
              properties:
                nombreCompleto:
                  type: string
                  example: Juan Pérez
                email:
                  type: string
                  example: juan.perez@example.com
                contrasena:
                  type: string
                  format: password
                  example: "123456"
                foto:
                  type: string
                  nullable: true
                  example: "https://example.com/fotos/juan.jpg"
      responses:
        "201":
          description: Usuario creado exitosamente
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: integer
                    example: 42
        "400":
          description: Datos inválidos o incompletos
        "500":
          description: Error del servidor

  /api/users/login:
    post:
      summary: Inicia sesión un usuario
      tags:
        - Usuarios
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - email
                - contrasena
              properties:
                email:
                  type: string
                  description: Correo electrónico del usuario
                contrasena:
                  type: string
                  format: password
            example:
              email: juan.perez@example.com
              contrasena: "123456"
      responses:
        "200":
          description: Autenticación exitosa
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                    example: true
                  message:
                    type: string
                    example: Bienvenido Juan Pérez
                  data:
                    type: object
                    properties:
                      id:
                        type: string
                        example: "19"
                      nombreCompleto:
                        type: string
                        example: Juan Pérez
                      email:
                        type: string
                        example: juan.perez@example.com
                      foto:
                        type: string
                        format: uri
                        example: https://example.com/fotos/juan.jpg
                      fechaCreacion:
                        type: string
                        format: date-time
                        example: "2025-05-17 12:19:54"
                      sessionToken:
                        type: string
                        example: JWT eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9...
        "400":
          description: Credenciales inválidas o faltantes
        "500":
          description: Error del servidor

  /api/users/logout:
    post:
      summary: Cierra la sesión del usuario
      tags:
        - Usuarios
      security:
        - jwtAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - id
              properties:
                id:
                  type: integer
                  example: 42
      responses:
        "200":
          description: Sesión cerrada exitosamente
        "401":
          description: Token no válido o no proporcionado
        "500":
          description: Error del servidor

  /api/users/{email}:
    get:
      summary: Verificar si un usuario existe
      tags:
        - Usuarios
      parameters:
        - in: path
          name: email
          required: true
          schema:
            type: string
          description: Correo electrónico del usuario a buscar
          example: juan.perez@example.com
      responses:
        "200":
          description: Usuario encontrado exitosamente
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: integer
                    example: 1
        "404":
          description: Usuario no encontrado
        "500":
          description: Error del servidor

  # MercadoPago
  /crear-preferencia:
    post:
      summary: Crea una preferencia de pago en Mercado Pago
      tags:
        - Pagos
      security:
        - jwtAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                items:
                  type: array
                  items:
                    type: object
                    required:
                      - id
                      - title
                      - quantity
                      - unit_price
                      - currency_id
                    properties:
                      id:
                        type: string
                        example: item-ID-1235
                      title:
                        type: string
                        example: Lomo Saltado
                      description:
                        type: string
                        example: Descripción del Item
                      category_id:
                        type: string
                        example: art
                      quantity:
                        type: integer
                        example: 2
                      unit_price:
                        type: number
                        format: float
                        example: 28.5
                      currency_id:
                        type: string
                        example: PEN
                      picture_url:
                        type: string
                        format: uri
                        example: https://www.mercadopago.com/org-img/MP3/home/logomp3.gif
              example:
                items:
                  - id: item-ID-1235
                    title: Lomo Saltado
                    description: Descripción del Item
                    category_id: art
                    quantity: 2
                    unit_price: 28.5
                    currency_id: PEN
                    picture_url: https://www.mercadopago.com/org-img/MP3/home/logomp3.gif
      responses:
        "200":
          description: Preferencia creada exitosamente
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: string
                    example: 1258945087-285a1143-a776-4b77-bb66-33471168744b
                  init_point:
                    type: string
                    format: uri
                    example: https://www.mercadopago.com.pe/checkout/v1/redirect?pref_id=1258945087-285a1143-a776-4b77-bb66-33471168744b
                  sandbox_init_point:
                    type: string
                    format: uri
                    example: https://sandbox.mercadopago.com.pe/checkout/v1/redirect?pref_id=1258945087-285a1143-a776-4b77-bb66-33471168744b
        "400":
          description: Datos inválidos o incompletos
        "500":
          description: Error interno del servidor
